Regular:
  prefix: '@'
  titles:
    enabled: true
    title-text: test
    subtitle-text: test
  actionbar:
    enabled: true
    actionbar-text: test
useOldWay: true
needPermissionToMention: false
needsPrefix: true
hooks:
  Essentials: true
  Factions: true
  mcMMO: true
  SuperVanish: true