main: net.hypexmon5ter.pm.PlayerMention
name: PlayerMention
author: HYPExMon5ter
version: pre4-3.3
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Essentials, FactionChat, mcMMO, SuperVanish, PremiumVanish, Skript, Marriage]

commands:
  playermention:
    description: This is a test command
    aliases: /pm