main: net.hypexmon5ter.pm.PlayerMention
name: PlayerMention
author: HYPExMon5ter
version: pre2-3.2
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Essentials, FactionChat, mcMMO, SuperVanish, PremiumVanish, Skript, AutoUpdaterAPI]